[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.7"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.7"
  source = "https://github.com/fsnotify/fsnotify"

[prune]
  go-tests = true
  unused-packages = true
